server.port: 9995

security:
  ignored: /open,/*.js,/sdoc.jsp,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*

spring.oauth2.resource:
  id: cloud_controller
  jwt:
    keyUri: ${vcap.services.sso.credentials.tokenKey}

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

cf:
  resource: ${vcap.services.sso.credentials.apiEndpoint}
  uaa: ${vcap.services.sso.credentials.uaaUri}

external-tools:
  others:
    - name: rstudio
      available: ${vcap.services.external-tools.credentials.rstudio.available}
    - name: gearpump
      available: ${vcap.services.external-tools.credentials.gearpump.available}
    - name: h2o
      available: ${vcap.services.external-tools.credentials.h2o.available}
  visualizations:
    - name: hue
      available: ${vcap.services.external-tools.credentials.hue.available}
      url: ${vcap.services.external-tools.credentials.hue.url}
    - name: arcadia
      available: ${vcap.services.external-tools.credentials.arcadia.available}
      url: ${vcap.services.external-tools.credentials.arcadia.url}
