server.port: 9995

security:
  ignored: /open,/*.js,/sdoc.jsp,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*,/v2/api-docs

spring.oauth2.resource:
  id: cloud_controller
  jwt:
    keyUri: ${vcap.services.sso.credentials.tokenKey}

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

cf:
  resource: ${vcap.services.sso.credentials.apiEndpoint}
  uaa: ${vcap.services.sso.credentials.uaaUri}
  cli:
    version: latest
    url: https://cli.run.pivotal.io/stable?release={RELEASE}&version={VERSION}

external-tools:
  visualizations:
    - name: hue
      available: ${vcap.services.external-tools.credentials.hue.available}
      url: ${vcap.services.external-tools.credentials.hue.url}
    - name: arcadia
      available: ${vcap.services.external-tools.credentials.arcadia.available}
      url: ${vcap.services.external-tools.credentials.arcadia.url}

endpoints.enabled: false
endpoints.health.enabled: true
